language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

script:
 - vendor/bin/phpunit

before_script:
 - composer install -n --prefer-source --dev

notifications:
  email:
    - me@mikevanriel.com
